### változók
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}
### @token = 12|ibiwTdr77o8ppToh1tBxIkckBNb8ECjIjLgaweTaa757cdef

### --- users
### login
# @name login
POST {{host}}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@minta.hu",
    "password": "123"
}
### login
# @name login
POST {{host}}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "vasarlo1@minta.hu",
    "password": "123"
}

###
@token = {{login.response.body.data.token}}


POST  {{host}}/api/users/logout
Accept: application/json
Authorization: Bearer {{token}}


### get minden
GET  {{host}}/api/seats/1
Accept: application/json
Authorization: Bearer {{token}}

### get minden by id
GET  {{host}}/api/tickets/3
Accept: application/json
Authorization: Bearer {{token}}

### --- games
### post games
POST {{host}}/api/seats
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "sector_id":  "1",
    "seat_number": "151",
    "row": "10",
    "col": "16"
}

### post seats
POST {{host}}/api/seats 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "sector_id":  "1",
    "seat_number": "1",
    "row": "1",
    "col": "1"
}

### post sectors
POST {{host}}/api/sectors 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "sector_number":  "302",
    "sector_price": "12000"
}

### post teams
POST {{host}}/api/teams 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "team_name":  "Ujszasz VVSE",
    "team_city": "Ujszasz"
}

### post tickets
POST {{host}}/api/tickets 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "user_id":  "3",
    "game_id": "3",
    "seat_id": "3",
    "status": "paid"
}

### delete 
DELETE {{host}}/api/games/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### patch
PATCH {{host}}/api/seats/37502
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
     "sector_id":  "2",
    "seat_number": "152",
    "row": "11",
    "col": "17"
}

### jegy post
POST {{host}}/api/tickets 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "user_id":  "69",
    "game_id": "411",
    "seat_id": "300001",
    "status": "cancelled"
}