### változók
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}
### @token = 12|ibiwTdr77o8ppToh1tBxIkckBNb8ECjIjLgaweTaa757cdef


### login
# @name login
POST {{host}}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "lakatosronaldo@example.com",
    "password": "1234"
}

###
@token = {{login.response.body.data.token}}

POST  {{host}}/api/users/logout
Accept: application/json
Authorization: Bearer {{token}}


### get minden
GET  {{host}}/api/tickets
Accept: application/json
Authorization: Bearer {{token}}

# ### post games
# POST {{host}}/api/games 
# Content-Type: application/json
# Accept: application/json
# Authorization: Bearer {{token}}

# {
#     "team_home_id":  "234",
#     "team_away_id": "6643",
#     "game_date": "2026. 03. 01. 05:00:00",
# }