### változók
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}
### @token = 12|ibiwTdr77o8ppToh1tBxIkckBNb8ECjIjLgaweTaa757cdef


### login
# @name login
POST {{host}}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "lakatosronaldo@example.com",
    "password": "1234"
}

###
@token = {{login.response.body.data.token}}


POST  {{host}}/api/users/logout
Accept: application/json
Authorization: Bearer {{token}}


### get minden
GET  {{host}}/api/tickets
Accept: application/json
Authorization: Bearer {{token}}

### get minden by id
GET  {{host}}/api/tickets/2
Accept: application/json
Authorization: Bearer {{token}}

### post games
POST {{host}}/api/games 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "team_home_id":  "4",
    "team_away_id": "1",
    "game_date": "2026.03.01. 22:00:00"
}

### post seats
POST {{host}}/api/seats 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "sector_id":  "1",
    "seat_number": "234",
    "row": "13",
    "col": "4"
}

### post sectors
POST {{host}}/api/sectors 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "sector_number":  "302",
    "sector_price": "12000"
}

### post teams
POST {{host}}/api/teams 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "team_name":  "Ujszasz VVSE",
    "team_city": "Ujszasz"
}

### post tickets
POST {{host}}/api/tickets 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "user_id":  "3",
    "game_id": "3",
    "seat_id": "3",
    "status": "paid"
}

### delete 
DELETE {{host}}/api/sectors/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### patch
PATCH {{host}}/api/sectors/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "sector_number":  "301",
    "sector_price": "150000"
}