### Változók
@protocol = http
@hostname = localhost
@port = 8000
@host = {{protocol}}://{{hostname}}:{{port}}

### Pingelés - az API elérhetőségének ellenőrzése
GET {{host}}/api/x
Accept: application/json

### Bejelentkezés
# @name login
POST {{host}}/api/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123"
}

### Token kinyerése a bejelentkezés válaszából
@token = {{login.response.body.data.token}}

### Kijelentkezés
POST {{host}}/api/users/logout
Accept: application/json
Authorization: Bearer {{token}}

### Csapatok listázása
GET {{host}}/api/teams
Accept: application/json

### Csapat létrehozása - admin token szükséges
POST {{host}}/api/teams
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "team_name": "Új Csapat",
  "team_city": "Budapest"
}

### Csapat módosítása - admin token szükséges
PATCH {{host}}/api/teams/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "team_name": "Módosított Csapat",
  "team_city": "Győr"
}

### Csapat törlése - admin token szükséges
DELETE {{host}}/api/teams/1
Accept: application/json
Authorization: Bearer {{token}}

### Mérkőzések listázása
GET {{host}}/api/games
Accept: application/json

### Mérkőzés létrehozása - admin token szükséges
POST {{host}}/api/games
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "team_home_id": 1,
  "team_away_id": 2,
  "game_date": "2026-09-21 19:00:00"
}

### Szektorok listázása
GET {{host}}/api/sectors
Accept: application/json

### Szektor létrehozása - admin token szükséges
POST {{host}}/api/sectors
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "T901",
  "sector_name": "T901",
  "sector_price": 12000
}

### Székek listázása
GET {{host}}/api/seats
Accept: application/json

### Jegyek listázása - bejelentkezés szükséges
GET {{host}}/api/tickets
Accept: application/json
Authorization: Bearer {{token}}

### Jegyfoglalás
POST {{host}}/api/tickets/book
Accept: application/json
Content-Type: application/json

{
  "game_id": 1,
  "user_id": 1,
  "seat_ids": [1, 2]
}
